name: update-stable

on:
  release:
    types: [published]
  workflow_dispatch: ~

permissions: {}

jobs:
  update-stable:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: '0'
      - name: Update stable git tag
        run: |
          git tag --force $STABLE_TAG ${GITHUB_REF##*/}
          git push origin --delete $STABLE_TAG
          git push origin $STABLE_TAG
        env:
          STABLE_TAG: v3
